{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "tracefox.fullname" . }}-secrets
  labels:
    {{- include "tracefox.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore }}
    kind: {{ .Values.externalSecrets.secretStoreKind | default "SecretStore" }}
  
  target:
    name: {{ include "tracefox.fullname" . }}-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        HYPERDX_API_KEY: {{ `"{{ .hyperdxApiKey }}"` }}
        CLICKHOUSE_PASSWORD: {{ `"{{ .clickhousePassword }}"` }}
        MONGO_URI: {{ `"{{ .mongoUri }}"` }}
  
  data:
    - secretKey: hyperdxApiKey
      remoteRef:
        key: {{ .Values.externalSecrets.hyperdxApiKeyPath }}
    
    - secretKey: clickhousePassword
      remoteRef:
        key: {{ .Values.externalSecrets.clickhousePasswordPath }}
    
    - secretKey: mongoUri
      remoteRef:
        key: {{ .Values.externalSecrets.mongoUriPath }}
{{- end }}
