apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tracefox.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tracefox.labels" . | nindent 4 }}
type: Opaque
stringData:
  HYPERDX_API_KEY: {{ .Values.secrets.hyperdxApiKey | quote }}
  MONGO_URI: {{ .Values.secrets.mongoUri | quote }}
  CLICKHOUSE_ADMIN_PASSWORD: {{ .Values.secrets.clickhouseAdminPassword | quote }}
