{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "clickhouse.fullname" . }}-admin-password
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore }}
    kind: {{ .Values.externalSecrets.secretStoreKind | default "SecretStore" }}
  
  target:
    name: {{ include "clickhouse.fullname" . }}-admin-password
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        password: {{ `"{{ .password }}"` }}
  
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.externalSecrets.adminPasswordPath }}
{{- end }}
